# Generated by Django 4.1.3 on 2022-11-07 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Corregimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.city', verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Id_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('TI', 'Targeta de Identidad'), ('CC', 'Cedula de Ciudania'), ('CE', 'Cedula de Extranjeria'), ('NIP', 'Numero de Identificacion Personal'), ('NUIP', 'Numero Unico de Identificacion Personal')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='MessageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('SEND', 'SEND'), ('RECIVED', 'RECIVED'), ('READ', 'READ'), ('SENDING...', 'SENDING...')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('phone', models.PositiveIntegerField(verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Publication_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('Sport', 'Sport'), ('Gardening', 'Gardening'), ('Home Appliances', 'Home Appliances')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RequestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('In progress', 'In progress'), ('Earring', 'Earring'), ('Completed', 'Completed'), ('Mistake', 'Mistake')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('corregimiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.corregimiento', verbose_name='Corregimiento')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Lastname')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('idnumber', models.PositiveIntegerField(verbose_name='Id_Number')),
                ('phone', models.PositiveIntegerField(default=0, verbose_name='Phone')),
                ('mail', models.EmailField(max_length=254, verbose_name='Mail')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('idType_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.id_type', verbose_name='Id_Type')),
                ('zone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.zone', verbose_name='Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('publication_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication', verbose_name='Publication_Id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.user', verbose_name='User_Id')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('requeststate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.requeststate', verbose_name='RequestState_Id')),
                ('score_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.score', verbose_name='Score')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.user', verbose_name='User_id')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('publication_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication', verbose_name='Publication_Id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.user', verbose_name='User_Id')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication_type', verbose_name='Publication_Type_Id'),
        ),
        migrations.AddField(
            model_name='publication',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.user', verbose_name='User_Id'),
        ),
        migrations.AddField(
            model_name='publication',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.zone', verbose_name='Zone'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.message', verbose_name='Message_Id')),
                ('publication_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication', verbose_name='Publication_Id')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.request', verbose_name='Request_Id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.user', verbose_name='User_id')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='messagestate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.messagestate', verbose_name='MessageState_Id'),
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.user', verbose_name='User_Id'),
        ),
    ]
