# Generated by Django 4.1.3 on 2022-11-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='phone',
            field=models.PositiveBigIntegerField(verbose_name='Phone'),
        ),
    ]
