# Generated by Django 4.1.3 on 2022-11-07 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_corregimiento_id_type_alter_city_description_zone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='MessageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('phone', models.PositiveIntegerField(verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Publication_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='RequestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='id_type',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('publication_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication', verbose_name='Publication_Id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.user', verbose_name='User_Id')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('requeststate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.requeststate', verbose_name='RequestState_Id')),
                ('score_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.score', verbose_name='Score')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.user', verbose_name='User_id')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.user', verbose_name='User_Id')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication_type', verbose_name='Publication_Type_Id'),
        ),
        migrations.AddField(
            model_name='publication',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.report', verbose_name='Report_Id'),
        ),
        migrations.AddField(
            model_name='publication',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.user', verbose_name='User_Id'),
        ),
        migrations.AddField(
            model_name='publication',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.zone', verbose_name='Zone'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.message', verbose_name='Message_Id')),
                ('publication_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication', verbose_name='Publication_Id')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.request', verbose_name='Request_Id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.user', verbose_name='User_id')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='messagestate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.messagestate', verbose_name='MessageState_Id'),
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.user', verbose_name='User_Id'),
        ),
    ]
