# Generated by Django 4.1.3 on 2022-11-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_message_messagestate_publication_publication_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestate',
            name='description',
            field=models.CharField(choices=[('1', 'SEND'), ('2', 'RECIVED'), ('3', 'READ'), ('4', 'SENDING...')], max_length=10),
        ),
    ]
